name: lint

on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
    branches: [main]
  pull_request:
    paths-ignore:
      - "**.md"
      - "LICENSE"
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup latest Python
        uses: actions/setup-python@v2
        with:
          python-version: "*"
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0
